### ISSUE TITLE
Add nvQuickTheme to list

### ISSUE THREAD

**Issue by david-poindexter** [DnnFree/awesome-dnn#2]
Hi, would you able to add nvQuickTheme to your wonderful list?  

- [Website](http://www.nvquicktheme.com/)

- [GitHub Repo](https://github.com/nvisionative/nvQuickTheme)

**Comment by erw13n** [comment]
For sure.
Fill free to update if you have other free modules/themes to share.

**Comment by EPTamminga** [comment]
## Hi Erwin Yulianto,

I found your DNN work on GitHub about Interesting stuff about DNN and I am impressed. You have collected a lot of links to interesting stuff and organized it.

I am one of the DNN MVP’s and part the group of enthusiastic DNN persons, all working as active DNN Community members doing a lot of different things with and for the community. And above all, be motivated by the **positive vibe** in the group.

One of the things we are working in is a **curated catalogue of interesting DNN material**: modules, themes, tools, video’s, skin objects, documentation. 

You can find the first setup [here](https://www.dnn-connect.org/community/community-extensions) 

I have blogged about our initiative [here](http://www.dnnsoftware.com/community-blog/cid/155581/where-do-i-find-an-open-source-module-for-)

Getting your awesome stuff info in the catalogue would be most useful. **Are you interested in getting involved?** 

Regards,
Ernst Peter

**Comment by erw13n** [comment]
@EPTamminga Thank you
I'm interest in DNN since 2007, and still enthusiast using it up till now.
Just let me know if you need a hand, I would love to get involve.

**Comment by EPTamminga** [comment]
@erw13n Do you have an email address I can use for communication? That is easier than comments in GitHub issues...

**Comment by erw13n** [comment]
I just mail you directly.
If you didn't get my email, just go to my profile, you'll see my email address there.

**Comment by EPTamminga** [comment]
I tried you profile email bevore, ni succes, I did not receive an email from you directly...

My email address is ernst.peter.tamminga AT xcess.nl. Please give that a try?
