### ISSUE TITLE
Please add the Aarsys Metro7 Theme package to your list

### ISSUE THREAD

**Issue by aarsys** [DnnFree/awesome-dnn#4]
Metro7 Skin Package html % complient for DNN Platform 7.x, 8.x and 9.x include 4 Colors (blue, green, orange and red)  can be downloaded for free at https://github.com/aarsys/aarsysmetro7skin/releases

**Comment by erw13n** [comment]
For sure.
Fill free to update if you have other free modules/themes to share.
